-- UP migration file for migration 1682201262-user 
CREATE TABLE users(
    pk_user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    email VARCHAR(128) NOT NULL,
    password TEXT,
    last_login TIMESTAMPTZ,
    created_at timestamptz DEFAULT NOW()::timestamptz
);
ALTER TABLE users
ADD CONSTRAINT username_unique UNIQUE(username);
ALTER TABLE users
ADD CONSTRAINT email_unique UNIQUE(email);