openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: Hello World!
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/STUFF"
info:
  title: BeyondLife Api
  description: The BeyondLife Api
  version: "0.1"
  contact: {}
tags: []
servers: []
components:
  schemas:
    STUFF:
      type: object
      properties:
        first:
          type: string
        second:
          type: string
      required:
        - first
        - second
