version: "3.9"
services:
  backend:
    image: ghcr.io/dopeshot/beyond-life/backend:main
    restart: "always"
    ports:
      - 3001:3001
    environment:
      - DB_USER_NAME=${BACKEND_DB_USER_NAME:-admin}
      - DB_USER_PW=${BACKEND_DB_USER_PW:-admin}
      - DB_DB=${BACKEND_DB_DB:-beyond_life}
      - DB_HOST=${BACKEND_DB_HOST:-db}
      - DB_PORT=${BACKEND_DB_PORT:-5432}
      - JWT_REFRESH_SECRET=${BACKEND_JWT_REFRESH_SECRET:-verysecret}
      - JWT_REFRESH_EXPIRE_TIME=${BACKEND_JWT_REFRESH_EXPIRE_TIME:-10d}
      - JWT_SECRET=${BACKEND_JWT_SECRET:-secret}
      - JWT_EXPIRE_TIME=${BACKEND_JWT_EXPIRE_TIME:-1h}
    links:
      - db:db
        
  frontend:
    image: ghcr.io/dopeshot/beyond-life/frontend:main
    restart: "always"
    ports:
      - 3000:3000
    links:
      - backend:backend

  db:
    image: postgres:15
    ports:
      - 5432:5432
    restart: "always"
    volumes:
      - postgres_data_volume:/var/lib/pgsql/data
      - ./db/setup:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=${PG_USER:-admin}
      - POSTGRES_PASSWORD=${PG_PW:-admin}
      - POSTGRES_DB=${PG_DB:-beyond_life}
    healthcheck:
      # Healthcheck is based on the fact that the final postgres instance (after setup)
      # runs with PID 1
      test: ["CMD-SHELL", "pidof postgres | grep -q 1 && exit 0 || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3

volumes:
  postgres_data_volume:
