version: "3.9"
services:
  backend:
    image: ghcr.io/dopeshot/beyond-life/backend:main
    restart: "always"
    ports:
      - 3001:3001
    environment:
      - DB_USER_NAME=${BACKEND_DB_USER_NAME:-admin}
      - DB_USER_PW=${BACKEND_DB_USER_PW:-admin}
      - DB_HOST=${BACKEND_DB_HOST:-db}
      - DB_PORT=${BACKEND_DB_PORT:-27017}
      - JWT_REFRESH_SECRET=${BACKEND_JWT_REFRESH_SECRET:-verysecret}
      - JWT_REFRESH_EXPIRE_TIME=${BACKEND_JWT_REFRESH_EXPIRE_TIME:-10d}
      - JWT_SECRET=${BACKEND_JWT_SECRET:-secret}
      - JWT_EXPIRE_TIME=${BACKEND_JWT_EXPIRE_TIME:-1h}
    links:
      - db:db
        
  frontend:
    image: ghcr.io/dopeshot/beyond-life/frontend:main
    restart: "always"
    ports:
      - 3000:3000
    links:
      - backend:backend

  db:
    image: mongo:6.0.8 
    ports:
      - 27017:27017
    restart: "always"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW:-admin}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
