version: "3.9"
services:
  backend:
    image: ghcr.io/dopeshot/beyond-life/backend:main
    restart: "always"
    ports:
      - 3001:3001
  db:
    image: postgres:15
    ports:
      - 5432:5432
    restart: "always"
    volumes:
      - postgres_data_volume:/var/lib/pgsql/data
    environment:
      - POSTGRES_USER=${PG_USER:-admin}
      - POSTGRES_PASSWORD=${PG_PW:-admin}
      - POSTGRES_DB=${PG_DB:-beyond_life}
    healthcheck:
      # Healthcheck is based on the fact that the final postgres instance (after setup)
      # runs with PID 1
      test: ["CMD-SHELL", "pidof postgres | grep -q 1 && exit 0 || exit 1"]
      interval: 60s
      timeout: 5s
      retries: 3
volumes:
  postgres_data_volume:
