version: "3.9"
services:
  backend:
    image: ghcr.io/dopeshot/beyond-life/backend:main
    restart: "always"
    ports:
      - 3001:3001
    environment:
      - DB_USER_NAME=${BACKEND_DB_USER_NAME:-admin}
      - DB_USER_PW=${BACKEND_DB_USER_PW:-admin}
      - DB_HOST=${BACKEND_DB_HOST:-db}
      - DB_PORT=${BACKEND_DB_PORT:-27017}
      - JWT_REFRESH_SECRET=${BACKEND_JWT_REFRESH_SECRET:-verysecret}
      - JWT_REFRESH_EXPIRE_TIME=${BACKEND_JWT_REFRESH_EXPIRE_TIME:-10d}
      - JWT_SECRET=${BACKEND_JWT_SECRET:-secret}
      - JWT_EXPIRE_TIME=${BACKEND_JWT_EXPIRE_TIME:-1h}
      - JWT_VERIFY_SECRET=${BACKEND_JWT_VERIFY_SECRET:-evenmoresecret}
      - JWT_VERIFY_EXPIRE_TIME=${BACKEND_JWT_VERIFY_EXPIRE_TIME:-1d}
      - BACKEND_DOMAIN=${BACKEND_BACKEND_DOMAIN:-http://localhost:3001}
      - MAIL_HOST=${BACKEND_MAIL_HOST:-smtp_server}}
      - MAIL_HOST_PORT=${BACKEND_MAIL_HOST_PORT:-25}
      - MAIL_IS_SECURE=${BACKLEND_MAIL_IS_SECURE:-false}
      - MAIL_AUTH_USERNAME=${BACKEND_MAIL_AUTH_USERNANE:-mail}
      - MAIL_AUTH_PW=${BACKEND_MAIL_AUTH_PW:-mail}
      - MAIL_DEFAULT_SENDE=${BACKEND_MAIL_DEFAULT_SENDER:-hello@siebtesleben.de}
      - NODE_ENV=${BACKEND_NODE_ENV:-development}
    links:
      - db:db
      - smtp_server:smtp_server

  frontend:
    image: ghcr.io/dopeshot/beyond-life/frontend:main
    restart: "always"
    ports:
      - 3000:3000
    links:
      - backend:backend

  smtp_server:
    image: rnwood/smtp4dev:v3
    ports:
      - "5000:80"
      - "25:25"
      - "143:143"
    environment:
      - RelayOptions__Login=${BACKEND_MAIL_AUTH_USERNANE:-mail}
      - RelayOptions__Password=${BACKEND_MAIL_AUTH_PW:-mail}

  db:
    image: mongo:6.0.8
    ports:
      - 27017:27017
    restart: "always"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PW:-admin}
      - MONGO_INITDB_DATABASE:=${MONGO_DB:-siebtesleben}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
