name: frontend-pipeline

on:
  push:
    branches:
      - "stable"
      - "main"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yml"
      - ".github/workflows/docker-build-and-push.template.yml"
      - ".github/workflows/setup.template.yaml"

jobs:
  setup:
    uses: ./.github/workflows/setup.template.yaml
    with:
      context: frontend

  audit:
    runs-on: ubuntu-latest
    # Only run on PRs against stable and on stable itself
    if: github.ref == 'stable' || github.base_ref == 'stable'
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: audit
        run: npm audit --omit=dev

  tests:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        command:
          - te:cli
          - tc:cli
    defaults:
      run:
        shell: bash
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: node modules
        run: npm ci --audit:false --cache ~/.npm --prefer-offline

      - name: fallback to babel
        run: cp .ci.babelrc .babelrc

      - name: Cypress run
        uses: cypress-io/github-action@v5
        timeout-minutes: 15
        with:
          working-directory: ./frontend
          start: npm run dev
          command: npm run ${{ matrix.command }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-test-reports
          path: |
            frontend/cypress/results/*
            frontend/cypress/reports/*
            frontend/cypress/screenshots/*
            frontend/cypress/videos/*

      - name: ls
        run: ls -a && pwd

      - name: ls2
        run: ls -a ..

      - name: rename report
        run: mv coverage/coverage-final.json coverage/coverage-final-${{ hashFiles('frontend/coverage/coverage-final.json') }}.json

      - uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: frontend/coverage/coverage-final-${{ hashFiles('frontend/coverage/coverage-final.json') }}.json

  merge-coverage-and-create-badge:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: coverage-artifacts
          path: coverage

      - name: ls
        run: ls coverage

      - name: merge coverages
        run: npx --yes istanbul-merge --out merged/coverage.json $(find coverage -type f )

      - name: output coverage report
        run: npx nyc report -t merged --reporter text

      - name: generate badge
        run: |
          cov=$(npx nyc report -t merged --reporter text-summary | grep -oP 'Statements\s+:\s+\K\d+')
          color=$(if (( cov > 90 )); then echo "brightgreen"; elif (( cov >= 80 )); then echo "green"; elif (( cov >= 70 )); then echo "yellow"; elif (( cov >= 50 )); then echo "orange"; else echo "red"; fi)
          npx --yes badge-maker coverage $cov $color > .github/badges/frontend-coverage.svg

      - name: Commit
        run: |
          git config user.name ${{ secrets.BOT_NAME }}
          git config user.email ${{ secrets.BOT_MAIL }}
          git add .github/badges/frontend-coverage.svg 
          git commit -m "generated" || echo "No changes to commit"

      - name: Push
        run: git push

  docker-build-and-push:
    needs: tests
    uses: ./.github/workflows/docker-build-and-push.template.yml
    with:
      context: frontend
